### ISSUE TITLE
ImportError: cannot import name 'fomutils' from 'TMatrixOpt

### ISSUE THREAD

**Issue by wjwalex** [smhooten/TMatrixOpt#1]
Hi,

I tried to run the Bragg mirror example but got the following error:

"File ".\run_opt.py", line 55, in <module>
    from TMatrixOpt import geometry, optimizer, fomutils
ImportError: cannot import name 'fomutils' from 'TMatrixOpt' (C:\Users\wenwa\AppData\Roaming\Python\Python38\site-packages\tmatrixopt-1.0-py3.8.egg\TMatrixOpt\__init__.py)".

I tried to look it up in TMatrixOpt file but couldn't find fomutils.py file. May I ask how to solve it?

**Comment by smhooten** [comment]
Hi,

Sorry about this, I had changed the name of that module recently and didn't update it in the examples.

Please git pull the most recent commits and run setup.py:
python setup.py install --user
Then try to run the Bragg mirror example again.

Let me know if there are any additional issues,
Sean

**Comment by wjwalex** [comment]
Hi, 

Thank you. Now it works!
